export const BASE_URL = 'http://www.mocky.io/v2/5c41920e0f0000543fe7b889';
export const GET_SEARCH_RESULT = 'GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_ERROR = 'GET_SEARCH_RESULT_ERROR';
export const GET_PROFILE_RESULT_SUCCESS = 'GET_PROFILE_RESULT_SUCCESS';
export const EMPTY_STORE = 'EMPTY_STORE';
